service: Attendance-Slack-Bot
frameworkVersion: ">=1.1.0 <2.0.0"
provider:
  name: aws
  runtime: python3.7
  region: us-east-1
plugins:
  - serverless-python-requirements
package:
  exclude:
    - .venv/**
    - .git/**
    - __pycache__/** # for python 3.x
    - node_modules/**
    - README.md
    - serverless.yml
    - package-lock.json
    - package.json
    - requirements/**
    - requirements.txt

functions:
  parseRequest:
    memorySize: 512
    handler: slack.parse_request
    events:
      - http:
          path: user
          method: post